-- Legacy shim: commands are now registered via require("reminders.commands").register()
-- This file is kept for backward compatibility but does nothing on its own.
-- All command registration happens in lua/reminders/commands.lua, called from setup().
